spring:

  application:
    name: vehicle-telemetry-service

  flyway:
    enabled: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

  endpoint:
    health:
      probes:
        enabled: true